name: Build on Flutter Android
repoFullName: prachi05kulkarni-prachi05kulkarni/Mini-Project-1B
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.workDir}}
    strategy:
      matrix:
        flutter-version:
          - 3.19.0
    steps:
      - name: Setup jobs
        uses: actions/checkout@v3
      - name: Setup Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: stable
      - name: GitHub Setup
        run: |
          git checkout .
          git checkout main
          git pull origin main
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: zulu
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Install Dependencie
        run: flutter pub get
      - name: Build APK
        run: |
          cd android/
          ./gradlew assembleRelease
      - name: Build ADB
        run: |
          cd android/
          ./gradlew bundleRelease
